# Generated by Django 4.2.11 on 2024-05-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('emailid', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('phonenumber', models.CharField(max_length=30)),
            ],
        ),
    ]
